services:

  backend:
    build: .
    container_name: test_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:7
    container_name: redis_db